CREATE ROLE atendimento_app
    WITH LOGIN PASSWORD 'atendimento'
    NOSUPERUSER NOCREATEDB NOCREATEROLE;

GRANT USAGE ON SCHEMA public TO atendimento_app;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO atendimento_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO atendimento_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO atendimento_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT USAGE, SELECT ON SEQUENCES TO atendimento_app;
